"""
Input/output functions for MRI data loading and user interaction.

This module handles:
- NIfTI file loading via nibabel
- ACQP file parsing to extract echo times
- GUI dialogs (tkinter) for file selection and manual TE entry
"""

import re

import nibabel as nib
import numpy as np
import tkinter as tk
from tkinter import Label, Text
from tkinter.filedialog import askopenfilename
from tkinter.ttk import Button


# ── NIfTI ─────────────────────────────────────────────────────────────────────

def load_nifti(filepath):
    """Load a NIfTI file and return its data array and image object.

    Parameters
    ----------
    filepath : str or os.PathLike
        Path to the ``.nii`` or ``.nii.gz`` file.

    Returns
    -------
    data : np.ndarray of shape (nx, ny, nz, n_te)
        4-D array of voxel intensities (float64).
    img : nibabel.Nifti1Image
        NIfTI image object, giving access to the affine matrix and header.

    Notes
    -----
    Calls ``sys.exit()`` if the file cannot be loaded, printing a diagnostic
    message to stdout. This behaviour is intentional for interactive CLI use
    and may be replaced with a raised exception in future versions.

    Examples
    --------
    >>> data, img = load_nifti("scan.nii.gz")
    >>> print(data.shape)   # (nx, ny, nz, n_te)
    """
    try:
        img = nib.load(filepath)
        data = img.get_fdata()
    except Exception:
        print("Aucune image chargée, fin de l'opération.")
        raise SystemExit(1)
    return data, img


def choose_nifti():
    """Open a GUI file-picker dialog to select a NIfTI file.

    Returns
    -------
    filepath : str
        Absolute path to the selected ``.nii`` or ``.nii.gz`` file.
        Returns an empty string if the dialog is cancelled.

    Notes
    -----
    Requires a graphical display. On headless servers, use ``load_nifti``
    directly with a hard-coded path.
    """
    root = tk.Tk()
    root.withdraw()
    filepath = askopenfilename(
        title="Select NIfTI file",
        filetypes=[("NIfTI files", "*.nii *.nii.gz"), ("All files", "*.*")],
    )
    root.destroy()
    return filepath


# ── ACQP ──────────────────────────────────────────────────────────────────────

def choose_acqp():
    """Open a GUI file-picker dialog to select a Bruker ACQP file.

    Returns
    -------
    filepath : str
        Absolute path to the selected ACQP file.
        Returns an empty string if the dialog is cancelled.
    """
    root = tk.Tk()
    root.withdraw()
    filepath = askopenfilename(
        title="Select ACQP file",
        filetypes=[("ACQP files", "acqp"), ("All files", "*.*")],
    )
    root.destroy()
    return filepath


def load_acqp(filepath):
    """Parse a Bruker ACQP file and extract echo times.

    Reads the ``##$ACQ_echo_time`` field from the ACQP parameter file
    generated by ParaVision.

    Parameters
    ----------
    filepath : str or os.PathLike
        Path to the ACQP file.

    Returns
    -------
    te_values : np.ndarray of shape (n_te,)
        Echo times in milliseconds, in acquisition order.

    Notes
    -----
    Calls ``sys.exit()`` if the file cannot be parsed.

    Examples
    --------
    >>> te = load_acqp("path/to/acqp")
    >>> print(te)   # e.g. [10. 20. 40. 80.]
    """
    try:
        with open(filepath) as f:
            text = f.read()
        match = re.search(
            r"##\$ACQ_echo_time=.*?\n([\s\S]*?)##\$", text
        ).group(1).split()
        te_values = np.array([float(e) for e in match])
        print(
            f"[TE] {len(te_values)} echo times loaded: "
            f"{te_values[0]:.1f} – {te_values[-1]:.1f} ms"
        )
    except Exception:
        print("Aucun fichier ACQP valide fourni.")
        raise SystemExit(1)
    return te_values


# ── Manual TE entry ───────────────────────────────────────────────────────────

def enter_te(data):
    """Open a GUI dialog for manual echo-time entry.

    Displays a small tkinter window where the user can type echo times
    separated by spaces or commas.

    Parameters
    ----------
    data : np.ndarray of shape (nx, ny, nz, n_te)
        MRI data array. Used only to check that the number of entered TE
        values matches ``data.shape[3]``.

    Returns
    -------
    te_values : np.ndarray of shape (n_te,)
        Echo times in milliseconds. Falls back to synthetic values
        (3, 6, 9, … ms) if input is invalid or length mismatches.

    Notes
    -----
    The fallback generates synthetic TEs spaced 3 ms apart, which may not
    reflect the actual acquisition and should only be used for quick
    exploratory analysis.
    """
    te_values = None

    def retrieve_te():
        nonlocal te_values
        user_input = text_box.get("1.0", "end").strip()
        if user_input:
            try:
                te_values = np.array(
                    [float(x) for x in user_input.replace(",", " ").split()]
                )
                root.destroy()
            except Exception:
                print("[TE] Invalid input — please enter numeric values.")

    root = tk.Tk()
    root.title("Enter echo times")
    root.geometry("280x170")

    text_box = Text(root, height=5, width=52)
    label = Label(root, text="Enter TE values (space or comma separated)")
    btn = Button(root, text="Confirm", command=retrieve_te)

    text_box.pack()
    label.pack()
    btn.pack()
    root.mainloop()

    n_echos = data.shape[3]
    if te_values is None or len(te_values) != n_echos:
        print("[TE] Length mismatch or no input — using synthetic TEs.")
        te_values = np.arange(1, n_echos + 1) * 3.0
        print(
            f"[TE] Synthetic TEs: {te_values[0]:.1f} – {te_values[-1]:.1f} ms"
        )
    return te_values


# ── TE source selection ───────────────────────────────────────────────────────

def handle_acqp(data):
    """Open a GUI dialog to choose how echo times are provided.

    Presents three options:
    - Load from an ACQP file
    - Generate synthetic TEs from the NIfTI shape
    - Enter TEs manually

    Parameters
    ----------
    data : np.ndarray of shape (nx, ny, nz, n_te)
        MRI data array. Used to infer the number of echoes for synthetic TE
        generation.

    Returns
    -------
    result : dict
        Dictionary with a single key ``"choice"`` whose value is one of
        ``"load"``, ``"generate"``, or ``"manual"``.

    Examples
    --------
    >>> choice = handle_acqp(data)
    >>> if choice["choice"] == "load":
    ...     te = load_acqp(choose_acqp())
    """
    result = {"choice": None}

    def set_choice(value):
        result["choice"] = value
        root.destroy()

    root = tk.Tk()
    root.title("Echo time source")
    root.minsize(220, 110)
    root.maxsize(220, 110)

    Button(
        root, text="Load ACQP file",
        command=lambda: set_choice("load")
    ).pack(pady=(10, 2))
    Button(
        root, text="Generate TE from NIfTI shape",
        command=lambda: set_choice("generate")
    ).pack(pady=2)
    Button(
        root, text="Enter TE manually",
        command=lambda: set_choice("manual")
    ).pack(pady=2)

    root.mainloop()
    return result